config/routes.rb
Rails.application.routes.draw do
  namespace :administer do
    resources :dashboard, :only => :index
    resources :entities
  end

  match 'administer', :to => 'administer/dashboard#index'
end

app/controllers/administer/application_controller.rb
module Administer
  class ApplicationController < ::ApplicationController
    layout 'administer'

    before_filter :configured_filter

    private
    def configured_filter
      self.send(:test_authorization)
    end
  end
end

app/controllers/administer/dashboard_controller.rb
module Administer
  class DashboardController < ApplicationController
    unloadable

    def index
    end
  end
end

app/controllers/administer/entities_controller.rb
module Administer
  class EntitiesController < ApplicationController
    unloadable
    before_filter :set_model
    before_filter :collection, :only => :index
    before_filter :fields, :only => [:new, :create, :edit, :update]

    def new
      @object = model_class.new
    end

    def create
      @object = model_class.new
      handle_has_one
      @object.attributes= @model_params
      if @object.save
        redirect_to administer_entities_path(:model_name => model_class.model_name)
      else
        render :new
      end
    end

    def edit
      @object = model_class.find(params[:id])
    end

    def update
      @object = model_class.find(params[:id])
      handle_has_one
      if @object.update_attributes(@model_params)
        redirect_to administer_entities_path(:model_name => model_class.model_name)
      else
        render :edit
      end
    end

    def destroy
      @object = model_class.find(params[:id])
      unless @object.destroy
        flash[:error] = "Could not destroy object."
      end
      redirect_to administer_entities_path(:model_name => model_class.model_name)
    end

    protected
    def model_class
      @model.entity
    end
    helper_method :model_class

    def set_model
      @model = Model.for(params[:model_name])
    end

    def collection
      @collection = model_class.all
    end

    def fields
      @fields = @model.fields
    end

    def handle_has_one
      has_ones = @fields.select{|f| f.is_a? Administer::Fields::HasOne }
      @model_params = params[model_class.model_name.underscore]
      has_ones.each do |o|
        if @model_params[o.foreign_key]
          has_one_id = @model_params.delete(o.foreign_key)
          if has_one_id.present?
            @object.send((o.name.to_s+"=").to_sym, o.association_class.find(has_one_id))
          end
        end
      end
    end
  end
end

app/controllers/administer/models_controller.rb
module Administer
  class Administer::ModelsController < ApplicationController
    unloadable
    before_filter :collection, :only => :index
    
    protected
    def model_class
      Administer::Model.lookup(params[:model_name])
    end
    helper_method :model_class
    
    def collection
      @collection = model_class.all
    end
  end
end

app/helpers/administer/dashboard_helper.rb
module Administer::DashboardHelper
  def administer_model_names
    Administer::Model.all.collect { |m| m.entity.model_name }
  end
end

app/helpers/administer/entities_helper.rb
module Administer::EntitiesHelper
end

app/views/administer/dashboard/index.html.haml
%h1
  Administer Dashboard
%h2
  Models:
%ul.administer_model_list
  - administer_model_names.each do |model_name|
    %li= link_to(model_name.human.pluralize, administer_entities_path(:model_name => model_name))

app/views/administer/entities/_form.haml
- fields.each do |field|
  %p
    = render field.partial, :field => field, :f => f, :form_object => object
    - if errors = object.errors[field.name]
      %span.errors
        - errors.each do |error|
          = error
          - unless errors.last == error
            %br

app/views/administer/entities/edit.html.haml
#edit
  %ul.actions
    %li= link_to('back', administer_entities_path(:model_name => model_class.model_name))
  %h1
    Edit
    = model_class.model_name.human
  = form_for @object, :url => administer_entity_path(@object, :model_name => model_class.model_name) do |f|
    = render 'form', :fields => @fields, :f => f, :object => @object
    = f.submit "Update #{model_class.model_name}"

app/views/administer/entities/index.html.haml
#index
  %ul.actions
    %li= link_to('back', administer_dashboard_index_path)
    %li= link_to("New #{model_class.model_name.human}", new_administer_entity_path(:model_name => model_class.model_name))
  %h1= model_class.model_name.human.pluralize
  %table.items_list
    %thead
      %tr
      - model_class.column_names.each do |column_name|
        %th= column_name
      %th Actions

    %tbody
      - @collection.each do |object|
        %tr{:class => cycle('odd', 'even')}
          - model_class.column_names.each do |column_name|
            %td= object.send(column_name).to_s
          %td
            %ul.actions
              %li= link_to("Edit", edit_administer_entity_path(object, :model_name => model_class.model_name))
              %li= button_to("Delete", administer_entity_path(object, :model_name => model_class.model_name), :method => :delete)

app/views/administer/entities/new.haml
#new
  %ul.actions
    %li= link_to('back', administer_entities_path(:model_name => model_class.model_name))
  %h1
    New
    = model_class.model_name.human
  = form_for @object, :url => administer_entities_path(:model_name => model_class.model_name) do |f|
    = render 'form', :fields => @fields, :f => f, :object => @object
    = f.submit "Create #{model_class.model_name}"

app/views/administer/fields/_belongs_to.html.haml
= f.label field.primary_key, field.name.to_s.humanize
= f.select field.primary_key, field.collection.map { |object| [field.display_object(object), object.id] }

app/views/administer/fields/_date_select.html.haml
= f.label field.name
= f.date_select field.name

app/views/administer/fields/_has_many.html.haml
%h2= field.name.to_s.humanize
- field.collection.each do |entity|
  = check_box_tag field.check_box_name, entity.id, field.checked?(@object, entity), :id => field.dom_id(entity)
  = label_tag field.dom_id(entity), field.display_object(entity)

app/views/administer/fields/_has_one.html.haml
= f.label field.dom_id, field.name.to_s.humanize
= select_tag field.select_name, options_for_select(field.options, form_object.send(field.name).try(:id)), {:id => field.dom_id}

app/views/administer/fields/_text_area.html.haml
= f.label field.name
= f.text_area field.name

app/views/administer/fields/_text_field.html.haml
= f.label field.name
= f.text_field field.name

app/views/administer/fields/_textarea.html.haml
= f.label field.name
= f.text_area field.name

app/views/administer/fields/_textfield.html.haml
= f.label field.name
= f.text_field field.name

app/views/administer/shared/_errors.html.haml
- if object.errors.any?
  #errorExplanation
    %h2= "#{pluralize(object.errors.count, 'error')} prohibited this #{object.class.model_name} from being saved:"
    %ul
    - object.errors.full_messages.each do |msg|
      %li= msg

app/views/layouts/administer.html.haml
!!! 5
%html
  %head
    %title Administer
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
    %style{:type => "text/css", :media => "screen"}
      :css
        #
  %body
    #adminiser
      .header
        %ul.navigation
          %li
            = link_to "Go to application", root_path
      .flash#error
        = flash[:error]
      .flash#notice
        = flash[:notice]
      = yield